USE [APP]
GO

/****** Object:  Table [Trd].[LU_DiligenceType]    Script Date: 12/21/2017 4:39:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Trd].[LU_DiligenceType](
	[ID] [tinyint] IDENTITY(1,1) NOT NULL,
	[TypeName] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [Trd].[LU_DiligenceType] ADD CONSTRAINT U_TypeName UNIQUE(TypeName)

SET ANSI_PADDING OFF
GO


